name: Auto-create PR
on:
  push:
    branches:
      - adobe

jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Auto-create documentation PR for changes authored by Adobe employees
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "adobe"
          TO_BRANCH: "main"
          PULL_REQUEST_TITLE: ${{github.event.head_commit.message}}
          PULL_REQUEST_BODY: "New documentation changes by Adobe employees"
      - name: Print actor
        run: echo ${{github.actor}}
  approve-pr:
    name: Auto Approve a PR by gihub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dplacinta'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
