name: Auto-create PR
on:
  push:
    branches:
      - adobe

jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Auto-create documentation PR for changes authored by Adobe employees
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Opening pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}} > PULL_REQUEST_NUMBER
      - name: Print actor
        run: echo ${{github.actor}} created a new pr
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dplacinta'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto approved automated PR"
          pull-request-number:  PULL_REQUEST_NUMBER 
    #approve-pr:
    # name: Auto Approve a PR by gihub Actions
    #runs-on: ubuntu-latest
    #    steps:
    #      - name: Auto-approve
    #        uses: hmarr/auto-approve-action@v2.0.0
    #       if: github.actor == 'dplacinta'
    #      with:
    #      github-token: ${{ secrets.GITHUB_TOKEN }}
