name: Auto-merge PR
on:
  pull_request:
#    types:
#      - labeled
#      - unlabeled
#      - synchronize
#      - opened
#      - edited
#      - ready_for_review
#      - reopened
#      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  auto-merge:
    name: Auto merge after successful checks
#    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.5
        if: github.actor == 'dplacinta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: rebase
          LOG: "TRACE"