name: Sync
on:
  push:
    branches:
      - adobe

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Auto-create documentation PR for changes authored by Adobe employees
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "adobe"
          TO_BRANCH: "main"
          PULL_REQUEST_TITLE: ${{github.event.head_commit.message}}
